account/urls.py
from django.contrib.auth.views import login, logout
from django.urls import path

from . import views


app_name = 'account'
urlpatterns = [
    path('', views.index, name='index'),
    path('entrar/', login, {'template_name': 'account/login.html'}, name='login'),
    path('sair/', logout, {'next_page': 'core:index'}, name='logout'),
    path('alterar-dados/', views.update_user, name='update_user'),
    path('alterar-senha/', views.update_password, name='update_password'),
    path('registro/', views.register, name='register'),
]

appcontroleestoque/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('conta/', include('account.urls')),
    path('catalogo/', include('catalog.urls')),
    path('admin/', admin.site.urls),
]

catalog/urls.py
from django.urls import path

from . import views

app_name = 'catalog'
urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:slug>', views.category, name='category'),
    path('produtos/<slug:slug>', views.product, name='product'),
]

core/urls.py
from django.urls import path

from . import views

app_name = 'core'
urlpatterns = [
    path('', views.index, name='index'),
    path('contato/', views.contact, name='contact'),
]

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.core.mail import send_mail
from django.conf import settings


class ContactForms(forms.Form):
    name = forms.CharField(label='Nome')
    email = forms.EmailField(label='E-mail')
    message = forms.CharField(label='Mensagem', widget=forms.Textarea)

    def send_mail(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        message = self.cleaned_data['message']
        message = 'Nome: {}\n' \
                  'E-Mail: {}\n' \
                  '{}'.format(name, email, message)
        send_mail(
            'Contato do Django E-Commerce', message, settings.EMAIL_HOST_USER,
            settings.DEFAULT_FROM_EMAIL
        )

core/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

from core.forms import ContactForms


class IndexView(TemplateView):
    template_name = 'index.html'


index = IndexView.as_view()


def contact(request):
    success = False
    form = ContactForms(request.POST or None)
    if form.is_valid():
        form.send_mail()
        success = True
        form = ContactForms(None)
    context = {
        'form': form,
        'success': success
    }
    return render(request=request, template_name='contact.html', context=context)

core/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-BR">
<head>
	<meta charset="utf-8">
	<title>{% block title %}Django E-Commerce{% endblock %}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<link rel="stylesheet" href="{% static 'assets/bootstrap.min.css' %}" media="screen" />
	<link rel="stylesheet" href="{% static 'assets/custom.min.css' %}" media="screen" />
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a href="" class="navbar-brand">Django E-Commerce</a>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav">
            <li>
              <a href="{% url 'core:index' %}">Início</a>
            </li>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="{% url 'catalog:product_list' %}" id="download">Categorias <span class="caret"></span></a>
              <ul class="dropdown-menu" aria-labelledby="download">
                  {% for category in categories %}
                  <li><a href="{{ category.get_absolute_url }}">{{ category.name }}</a></li>
                  {% endfor %}
              </ul>
            </li>
			<li>
				<a href="{% url 'core:contact' %}">Contato</a>
			</li>
          </ul>
          <ul class="nav navbar-nav navbar-right">

              <li><a href="{% url 'admin:index' %}">Admin</a></li>
              {% if user.is_authenticated %}
              <li><a href="{% url 'account:index' %}">Minha Conta</a></li>
              <li><a href="{% url 'account:logout' %}">Sair</a></li>
              {% else %}
              <li><a href="{% url 'account:login' %}">Entrar</a></li>
              <li><a href="{% url 'account:register' %}">Registrar</a></li>
              {% endif %}

          </ul>
        </div>
      </div>
    </div>
    <div class="container margin-top">
        {% block container %}{% endblock %}
		<footer>
			<div class="row">
			  <div class="col-lg-12">
			    <ul class="list-unstyled">
			      <li class="pull-right"><a href="#top">Voltar ao Topo</a></li>
			      <li><a href="{% url 'core:index' %}">Início</a></li>
			      <li><a href="{% url 'catalog:product_list' %}">Produtos</a></li>
			      <li><a href="{% url 'core:contact' %}">Contato</a></li>
			      <li><a href="">Termos e Privacidade</a></li>
			    </ul>
			  </div>
			</div>
		</footer>
	</div>
	<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{% static 'assets/bootstrap.min.js' %}"></script>
</body>
</html>

core/templates/contact.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}
    Contato | {{ block.super }}
{% endblock %}

{% block container %}
<div class="page-header">
    <h1>Fale conosco</h1>
    {% if success %}
    <div class="alert alert-success">
        Mensagen enviada com sucesso!
    </div>
    {% endif %}
    <form class="form-horizontal" action="" method="post">

        {% csrf_token %}

        <fieldset>

            {% for field in form %}
            <div class="form-group{% if field.errors %} has-error{% endif %}">
                <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
                <div class="col-md-9">
                    {% render_field field class='form-control' %}
                    {% if error in field.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endif %}
                </div>
            </div>
            {% endfor %}

            <div class="form-group">
                <div class="col-md-9 col-md-offset-3">
                    <button type="submit" class="btn btn-primary">Enviar</button>
                </div>
            </div>

        </fieldset>
    </form>
</div>
{% endblock %}

core/templates/index.html
{% extends "base.html" %}

{% block container %}
<div class="jumbotron page-header">
  <h1>{{ title|capfirst }}</h1>
  <p>Pagina inicial do projeto</p>
  <p>Em construção...</p>
  <p><a class="btn btn-primary">Saiba mais</a></p>
</div>
{% endblock %}

core/templates/pagination.html
<div class="row">
    <div class="col-md-12">
        <nav>
            <ul class="pagination">
                {% for page in paginator.page_range %}
                <li><a href="?page={{ page }}">{{ page }}</a></li>
                {% endfor %}
            </ul>
        </nav>
    </div>
</div>